# Generated by Django 3.2.8 on 2023-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='ide',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='cuenta',
            table='cuentas',
        ),
    ]
