# Generated by Django 3.2.8 on 2023-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontable', '0002_auto_20231026_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='totalDebe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='totalHaber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
