# Generated by Django 3.2.8 on 2023-10-27 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontable', '0003_auto_20231026_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('concepto', models.CharField(max_length=20)),
                ('nomCuenta', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
    ]
